server:
  port: 8082

spring:
  application:
    name: product-service

  datasource:
    # url: jdbc:postgresql://postgres-user:5432/userdb   # original commented URL
    url: jdbc:postgresql://localhost:5433/productdb
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: my_super_secret_key_that_is_long_enough_123456

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always

